### ISSUE TITLE
Feature Request: Don't require me to connect my account just to view.

### ISSUE THREAD

**Issue by MicahZoltu** [Ondkloss/uniswapdelegates#1]
Use something like Infura or your own Ethereum client hosted in the cloud to provide the user with an immediate experience without needing to connect.  Once the user connects, switch over to their connected wallet.

**Comment by Ondkloss** [comment]
Thanks for the input. Great idea, I'll look into it!

**Comment by Ondkloss** [comment]
My latest commit should address this, so everyone gets an immediate experience! Thanks for the tip @MicahZoltu!
